.mise-cache: &mise-cache
  key:
    prefix: mise-
    files: ["mise.toml", "./bin/mise"]
  paths:
    - .mise/installs
    - .mise/mise-2026.6.10

build-job:
  stage: build
  image: debian:12-slim # Use the image you created
  before_script:
    - apt-get update 
    - apt-get -y --no-install-recommends install sudo curl git ca-certificates build-essential pkg-config libssl-dev
    - rm -rf /var/lib/apt/lists/*
  cache:
    - <<: *mise-cache
      policy: pull-push
  script:
    - ./bin/mise install
    - ./bin/mise run compile-pdf
  artifacts:
    paths:
      - ./build/main.pdf
    # expire_in: 30 days 